import { GoogleGenAI } from "@google/genai";

// Initialize the client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Generates an edited version of the image based on the prompt.
 * Uses gemini-2.5-flash-image ("Nano banana").
 */
export const editImageWithGemini = async (
  base64Image: string, 
  prompt: string
): Promise<string> => {
  try {
    // Determine MIME type from base64 string or default to png if not present
    // Base64 string usually comes as "data:image/png;base64,..."
    const matches = base64Image.match(/^data:(.+);base64,(.+)$/);
    
    let mimeType = 'image/png';
    let data = base64Image;

    if (matches && matches.length === 3) {
      mimeType = matches[1];
      data = matches[2];
    } else {
      // Clean raw base64 if no header
      data = base64Image.replace(/^data:image\/\w+;base64,/, "");
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt,
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: data,
            },
          },
        ],
      },
    });

    // Parse the response to find the image part
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini Image Gen Error:", error);
    throw error;
  }
};